import { test, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// ---------------------------------------------------------------------------
//  The version string used to be hand-written in six places and nothing kept
//  them in sync. package.json reached 0.4.0 while the MCP server handshake and
//  all three native helpers still reported "0.1.0" — three minor releases of
//  drift, invisible because the helpers are separate C/C++/ObjC binaries that no
//  TS test reads and the server's `version` only surfaces in the MCP initialize
//  handshake.
//
//  package.json is now the single source of truth and the other sites are
//  DERIVED, so this file's job changed. It no longer regexes literals hoping a
//  human updated each one; it asserts that nothing hand-writes a version any
//  more, and that the derived artifacts agree. The difference matters: the old
//  test could only fail AFTER someone had edited five files and missed the
//  sixth, whereas there is now nothing to miss.
//
//  How each site gets its version:
//    native helpers  compile-time -DOBSBOT_VERSION, read from package.json by
//                    native/cmake/ObsbotVersion.cmake (and the macOS Makefile)
//    src/version.ts  generated by scripts/sync-version.mjs, run on prebuild
//    server.json     rewritten by the same script, run on `npm version`
// ---------------------------------------------------------------------------

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p: string): string => readFileSync(join(repoRoot, p), "utf8");

const pkgVersion = JSON.parse(read("package.json")).version as string;

test("package.json carries a plain semver version", () => {
  expect(pkgVersion).toMatch(/^\d+\.\d+\.\d+$/);
});

test("package-lock.json agrees with package.json", () => {
  // Found 2026-08-01 by bumping the version and watching what moved: the
  // lockfile was pinned at 0.4.1 while package.json was 0.6.2 — two releases of
  // drift in a file that ships in the tarball and that the old regex-based test
  // never looked at. `npm version` keeps both in step, so this only fails if
  // package.json is edited by hand; `npm install --package-lock-only` fixes it.
  const lock = JSON.parse(read("package-lock.json"));
  expect(lock.version).toBe(pkgVersion);
  expect(lock.packages?.[""]?.version).toBe(pkgVersion);
});

// ---------------------------------------------------------------------------
//  Derived artifact: src/version.ts
// ---------------------------------------------------------------------------

test("src/version.ts is generated in sync with package.json", () => {
  // If this fails, `npm run build` (or `node scripts/sync-version.mjs`) fixes
  // it — the file is generated, not maintained.
  const match = read("src/version.ts").match(/export const VERSION = "(\d+\.\d+\.\d+)"/);
  expect(match, "no VERSION export found in src/version.ts").not.toBeNull();
  expect(match![1]).toBe(pkgVersion);
});

test("the MCP handshake uses the generated VERSION rather than a literal", () => {
  // The handshake version is what clients see. A literal here would reintroduce
  // exactly the drift this setup removes, and it would be invisible until
  // someone read an initialize response.
  const server = read("src/mcp/server.ts");
  expect(server).toMatch(/version:\s*VERSION/);
  expect(server, "server.ts hard-codes a version").not.toMatch(/version:\s*"\d+\.\d+\.\d+"/);
});

// ---------------------------------------------------------------------------
//  Native helpers: no literals, and a build that cannot supply the version must
//  fail rather than default.
// ---------------------------------------------------------------------------

const HELPERS: Array<[label: string, path: string]> = [
  ["windows helper", "native/windows/helper.cpp"],
  ["linux helper", "native/linux/helper.c"],
  ["macos helper", "native/macos/helper.m"],
];

test.each(HELPERS)("%s takes its version from OBSBOT_VERSION, not a literal", (_label, path) => {
  const src = read(path);
  expect(src, `${path} does not reference OBSBOT_VERSION`).toMatch(/OBSBOT_VERSION/);
  // A bare semver inside a version JSON payload means someone reintroduced a
  // hand-edited literal. Matching on the surrounding \"version\": key keeps
  // this from tripping over unrelated version numbers in comments.
  expect(src, `${path} hard-codes a version`).not.toMatch(/version\\":\\"\d+\.\d+\.\d+/);
});

test.each(HELPERS)("%s refuses to build without OBSBOT_VERSION", (_label, path) => {
  // Defaulting is how the original drift went unnoticed for three releases: a
  // helper that silently reports a wrong version is worse than one that fails
  // to compile, because the wrong value travels to clients over the handshake.
  expect(read(path)).toMatch(/#\s*ifndef\s+OBSBOT_VERSION[\s\S]{0,200}#\s*error/);
});

test.each([
  ["linux", "native/linux/CMakeLists.txt"],
  ["windows", "native/windows/CMakeLists.txt"],
  ["macos", "native/macos/CMakeLists.txt"],
])("%s CMakeLists injects OBSBOT_VERSION from package.json", (_label, path) => {
  const src = read(path);
  expect(src).toMatch(/ObsbotVersion\.cmake/);
  expect(src).toMatch(/OBSBOT_VERSION="\$\{OBSBOT_VERSION\}"/);
});

test("the macOS Makefile injects the version too", () => {
  // A fourth build path, easy to forget: `make -C native/macos` is what local
  // macOS development uses, and helper.m #errors without the define.
  const mk = read("native/macos/Makefile");
  expect(mk).toMatch(/VERSION_DEF\s*:=\s*-DOBSBOT_VERSION/);
  expect(mk).toMatch(/package\.json/);
});

// ---------------------------------------------------------------------------
//  server.json is the MCP Registry's copy of the same facts, and it drifts in
//  two ways the sites above cannot: it carries the version twice (the server's
//  own, and the npm package's), and its `name` has to equal package.json's
//  `mcpName` or the registry rejects the publish with "you do not have
//  permission to publish this server". Both are parsed rather than regexed —
//  it is our JSON, so there is no reason to read it as bytes.
// ---------------------------------------------------------------------------

const pkg = JSON.parse(read("package.json"));
const serverJson = JSON.parse(read("server.json"));
const npmPackage = serverJson.packages?.find((p: { registryType: string }) => p.registryType === "npm");

test("server.json declares the same version as package.json", () => {
  expect(serverJson.version).toBe(pkgVersion);
});

test("server.json's npm package entry pins the published version", () => {
  expect(npmPackage, "no npm package entry in server.json").toBeDefined();
  expect(npmPackage.identifier).toBe(pkg.name);
  expect(npmPackage.version).toBe(pkgVersion);
});

test("server.json name matches package.json mcpName", () => {
  // The registry verifies npm ownership by reading mcpName out of the published
  // tarball's package.json and comparing it to this name. A mismatch is only
  // discovered at publish time, on a tag, after npm has already gone out.
  expect(pkg.mcpName).toBe(serverJson.name);
});
